# .streamlit/secrets.toml
# Make sure there are no spaces around the equal sign for spreadsheet_id

spreadsheet_id="1sykC70m5NhmUDfR2lwHksEgCcgItk_xr5ZNmUyj_YPw"

[gcp_service_account]
type = "service_account"
project_id = "qual-responses"
private_key_id = "057cef191adae0dee24c23343316678bbf2401a0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC9Sa6O7U2OWY2v
O5dIsfP8F0KuyKK0RBRFzLv+z+R7IlnNaC1eZpdqJ8VCfIP48Lr93Nawj5HlBTFr
XIcdMtkNCng3q1PdzU3uDxM9XVDTZkniEbpHIFjgKLWBbhmpgVCVGpOJgHXy5Jtd
LPRgZfGguC1nrpFxvTwXDeZlQd+TZU5LM6bmfxyGhNWoO/DhQti6DKzSvFnK3yWp
PmsUtdjNj7Xq/UqaeZqxnROik8upMiBgf+AmVoPo9Mqm8EL7M8BeqWprWV5mNXCm
dltypyQ9Z9C7+CNkIW4oS3Wpk57na67s+erzbDzE/EhO0G6TgPvK7XPO2ITzVCmS
XpSI+tqjAgMBAAECggEABp20ruThzmqYO9pmsfEbs2FSFgSH61UV1aVk93BnbrEH
V9lJp1Wz+nnkDdbcUK8ur1YwtYB50Poa0sMr1dFuf2OGStZ/hUPPyCpZZHkGgjJp
ErBxRQXUasFW1sH1E6pOxBIRu2n0tXCtctbyE7cnIumibKVQCscFJVPPDGr+WDXQ
JkTi07iouOZamxP4FhMLiJBCOo8OFpJcBrIGG9+AuXEexuYKiuHVGN6K3DQYn5VF
nzvLnEYjLWoudFOn8Din7WU2ae2wwnNTkt2H6319Ywe33fknIQEO1TrdzgZb1Bn1
OZlcTsPCl0OGWVpHNksey2Wd01guv4omvN/Fye0ygQKBgQDwsiRXERfkb6nE/di9
ZS6hkj16/bxEdKkEHATqQ15jB8pnMT9Q+1wD/bBEc66zcUdfylfGvlg9ScVanJLW
V8jPkmUln2MCPtzbj7Zk0IKC1rRlr4O3334f9oe0WO+NbJZ8QZXotVUW8EI1bZJ9
QCkey0rx/nENjFuo5/gWwHwsCwKBgQDJUsKZFDGsvUExSbChhijlsMXxJQZE/MFQ
hWVfFBE1l6ta8TtH5dqJSbiJb/roH7bpNbzKuI/FetLqsZ3qkN+/i1HZmu0ecpYy
DMqtzVj78QIR5n37hOpArUDh/2ly9Kw4h8lFlM6TwsIWzhk5FbCzcPxfbyyFvP+M
sgRxX9qSyQKBgAu+xaMyBFZzVHd2Y6MqUtIzjqh3xT4Z6z12GI9N5kcy1B+g+ZP8
EAtpz7YnZvj+qBr2hr39/9RNy0GWrlujQPtQC3uAgZZUdvaH1sCopBW6YGct32GT
mFX687hLNrVR/S3nDWejoZlS9AgjZqiR/u+vv+J7Jg0hMj/VwfdqQSTtAoGAYSey
R4OKUW1np6yDM//1fpsney897k73z68Ac7jQcUeHZzThQdo382cDSjgjIqAjejn3
qPEWWNvkK2SZ69gMUniegGAWrEnqF686pFNj7Pmq4Q6Vn6rODXZOyIGk1tgiwIku
5YhhhMdJOQ4u9/ByvLX65OdW2heST8idAkWaypkCgYA7sZALohLaoRcQvDOmN7WA
Gy7f5gvuq1sD2G5LMMrPfDdqZI42u1pyrUKVt3Z1xX8e3dNjwPxQ6C7fhvIRjXHY
RWj+/+cNPWlL831VtVJt8oDTuSAy9dUoYsEEepXQ05HbKeHV3WiKOFB89rA2CWly
QtukjsA7FV1C0G29DPc/Fw==
-----END PRIVATE KEY-----"""
client_email = "word-validation-app@qual-responses.iam.gserviceaccount.com"
client_id = "117518779436503197149"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/word-validation-app%40qual-responses.iam.gserviceaccount.com"
